### ISSUE TITLE
Request Hardware Tutorial

### ISSUE THREAD

**Issue by MrTanoshii** [wemos/LOLIN_EPD_Library#4]
Hi I'm trying to hook up a Wemos D1 mini (no TFT shield, just regular old hookup wire)
I have not being able to display anything or even blank out the default lolin factory sent displayed text.

I have tried the following configurations

EPaper - D1 mini

3.3V - 3.3V
GND - GND
RST - RST
CS - D0 (I've also tried D4 after reading mike2nl's post)
DC - D8

I've tried both examples

Edit: I've also tried powering the EPD module from an external source and not from the d1 mini 3.3V pin but nothing seems to work

**Comment by mike2nl** [comment]
@MrTanoshii 
that's from the example:
#define EPD_CS D0
#define EPD_DC D8 (D4 depeninding on your choice)
!!! -> #define EPD_RST -1  // can set to -1 and share with microcontroller Reset!

have you wired the reset to the display?

**Comment by MrTanoshii** [comment]
Yes I did. I was only able to get it to work using the full configuration, that is everything connected on the epaper side (BUSY unconnected as I am using the delay method)

As such I am also using this to instantiate the EPD object.
`LOLIN_IL3897 EPD(EPD_PIXEL_X, EPD_PIXEL_Y, EPD_MOSI_PIN, EPD_CLK_PIN, EPD_DC_PIN, EPD_RST_PIN, EPD_CS_PIN, EPD_BUSY_PIN);`


If you managed to use CS and DC only, please let me know your exact hardware configuration so I may try to replicate it. I'm using the wemos d1 mini to control it by the way.

**Comment by kd8bxp** [comment]
HI - I want to put my 2 cents in - I am using the TFT&I2C connector shield and was having problems getting this to work, I am using the default settings for the connector - so what worked for me was
```
/*D1 mini*/
#define EPD_CS D4
#define EPD_DC D3
#define EPD_RST -1  // can set to -1 and share with microcontroller Reset!
#define EPD_BUSY -1 // can set to -1 to not use a pin (will wait a fixed delay)
```
I am getting a lot of black flashing on the screen before an image or text loads and is readable, is this normal?

**Comment by MarkPieterdeJonge** [comment]
Hello,
D8 is connected to GPIO15 on WEMOS D1 Mini. GPIO15 has a pulldown for normal startup after reset. When i connected DC to D8 it doesnt reset normally but goes in a different boot mode.
My advice: dont use D8.
Hope this solves some issues for someone. Took me a while to figure out.
